### ISSUE TITLE
Is this map size limit reasonable?

### ISSUE THREAD

**Issue by krofna** [krofna/Warrior-of-Dreamworld-r3#5]
I was thinking of limiting maps to (2^16 / 32)^2 = 2048 tiles
So map would be at most 2048 32px tiles wide and 2048 32px tiles high. Is this limit reasonable or for some reason we need more than this?

**Comment by krofna** [comment]
Meh. I put this limit. Its practical :)
WE NEED TO DISCUSS MORE STUFF; IRC NOW!

**Comment by RaitoBezarius** [comment]
I'm still at school me :DD.

**Comment by krofna** [comment]
AAAAAAAAAAAAAAAAAAAAA.
But really, we do.

**Comment by RaitoBezarius** [comment]
There is still two days.

**Comment by krofna** [comment]
one more day :D

**Comment by RaitoBezarius** [comment]
Yep :D.

**Comment by krofna** [comment]
Aaand you can write code now? :D

**Comment by RaitoBezarius** [comment]
Not much :D.
I have final exam (Thursday and Friday), and prog contest (the next weekend)
After that, I think that I can.
Besides, from 4 to 8 July, I will be at Japan Expo, I WANNA SEE THE WRITER OF SAO ___
And... Have some fun with my friends and my girlfriend ! ^_^
SORRY.
BUT I PROMISE YOU.
AFTER ALL THAT.
I'LL CODE LIKE A GOD.

**Comment by krofna** [comment]
FIX CONFIG LOADING ASAP :dango: ^-^

**Comment by RaitoBezarius** [comment]
Excuse me. Sir. But... It works. Config Loading works as it should. BUUUUUUUUUUUUUUT.
PATHFINDER IS MAKING SERVER CRASH AT GRID<NODE>::RESIZE.
Give me your backtrace. I give you mine.
Backtrace : 

```
#6  0x00007ffff6de0627 in std::__throw_length_error(char const*) () from /usr/lib/libstdc++.so.6
#7  0x0000000000559f14 in std::vector<Node*, std::allocator<Node*> >::_M_check_len (this=0x7c9500, __n=18446744073709420545, __s=0x57af11 "vector::_M_fill_insert") at /usr/include/c++/4.8.1/bits/stl_vector.h:1339
#8  0x000000000055ddd9 in std::vector<Node*, std::allocator<Node*> >::_M_fill_insert (this=0x7c9500, __position=<error reading variable: Cannot access memory at address 0x0>, __n=18446744073709420545, __x=@0x7fffffffe518: 0x0)
    at /usr/include/c++/4.8.1/bits/vector.tcc:481
#9  0x000000000055d56e in std::vector<Node*, std::allocator<Node*> >::insert (this=0x7c9500, __position=<error reading variable: Cannot access memory at address 0x0>, __n=18446744073709420545, __x=@0x7fffffffe518: 0x0)
    at /usr/include/c++/4.8.1/bits/stl_vector.h:1024
#10 0x000000000055c9eb in std::vector<Node*, std::allocator<Node*> >::resize (this=0x7c9500, __new_size=18446744073709420545, __x=@0x7fffffffe518: 0x0) at /usr/include/c++/4.8.1/bits/stl_vector.h:687
#11 0x000000000055c13f in Grid<Node>::Resize (this=0x7c94f8, x=65535, y=65535) at /home/raito/Developpement/Warrior-of-Dreamworld-r3/Build/../Shared/Grid.hpp:69
#12 0x000000000055bad1 in Grid<Node>::Allocate (this=0x7c94f8, x=65535, y=65535) at /home/raito/Developpement/Warrior-of-Dreamworld-r3/Build/../Shared/Grid.hpp:75
#13 0x000000000055ac00 in Pathfinder::Pathfinder (this=0x7c9470) at /home/raito/Developpement/Warrior-of-Dreamworld-r3/Server/AI/Pathfinder.cpp:40
#14 0x0000000000536f87 in Singleton<Pathfinder>::CreateInstance<>() () at /home/raito/Developpement/Warrior-of-Dreamworld-r3/Build/../Shared/Singleton.hpp:40
#15 0x0000000000534fd9 in World::World (this=0x7c8fc0) at /home/raito/Developpement/Warrior-of-Dreamworld-r3/Server/World/World.cpp:46
#16 0x0000000000543c3d in Singleton<World>::CreateInstance<>() () at /home/raito/Developpement/Warrior-of-Dreamworld-r3/Build/../Shared/Singleton.hpp:40
#17 0x000000000053ca7a in Main::Main (this=0x7c8e00, r_io=...) at /home/raito/Developpement/Warrior-of-Dreamworld-r3/Server/World/Main.cpp:30
#18 0x000000000054458c in Singleton<Main>::CreateInstance<boost::asio::io_service&> () at /home/raito/Developpement/Warrior-of-Dreamworld-r3/Build/../Shared/Singleton.hpp:40
#19 0x000000000053d63a in main (argc=1, argv=0x7fffffffe828) at /home/raito/Developpement/Warrior-of-Dreamworld-r3/Server/World/Main.cpp:127
```

**Comment by krofna** [comment]
I will look into it when I'm on my computer.. But config didn't work for me! Maybe I forgot to update it...
Looks like I'm allocating a bit too much memory for pathfinder (Roughly 4GB according to backtrace... Do you have that much ? :D) My bad :(

**Comment by krofna** [comment]
#wod-dev whenever you can

**Comment by krofna** [comment]
Something else is eating RAM and its NOT pathfinder (I reduced perfection of pathfinder)

**Comment by krofna** [comment]
Help :P

**Comment by krofna** [comment]
wod-dev sometimes?

**Comment by RaitoBezarius** [comment]
I was in Japan Expo ! "Besides, from 4 to 8 July, I will be at Japan Expo, I WANNA SEE THE WRITER OF SAO"
I GET MY FIRST KISS 8DDDDDDDDDDD
I M HAPPY AND READY TO WORK.

**Comment by krofna** [comment]
:DDDDDDDDDDDDDDDDDDDD :DDDDDDDDDD
YOU WIN AT REAL LIFE.
